create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id text not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_conversation_id_idx
on public.messages (conversation_id, created_at);

alter table public.messages enable row level security;

grant select, insert on table public.messages to service_role;
grant usage, select on sequence public.messages_id_seq to service_role;